# Generated by Django 5.2.1 on 2025-05-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
