# Generated by Django 5.2.1 on 2025-05-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpost', '0002_rename_owner_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
    ]
