# Generated by Django 5.2.1 on 2025-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpost', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
