# Generated by Django 5.2.1 on 2025-05-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpost', '0006_rename_user_post_owner_post_image_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
