# Generated by Django 5.2.1 on 2025-05-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpost', '0008_post_likes_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
